// src/components/Header.svelte
<script>
  import { Link } from 'svero'
  const { random, floor } = Math
  const titles = [
    'Dada-driven developer',
    'It\'s buggier on the inside',
    'Stuff I\'m learning to play with',
  ]
  export let title = titles[floor(random() * titles.length)]
</script>

<div class="w-100 relative flex flex-column items-center justify-center pt3">
  <Link href="/" class="pa2 f1 no-underline black">Grokked it!</Link>
  <div class="pa2 f4">{title}</div>
</div>

// src/components/Header.tsx
import * as React from 'react'

interface Props {
  leftButton: () => void
  rightButton: () => void
}

export function Header(p: Props) {
  return (
    <div className="w-100 relative flex flex-column items-center justify-center pt3">
      <div className="pa2 f1">Grokked it!</div>
      <div className="pa2 f4">{"Stuff i'm learning to play with"}</div>
      <div className="absolute left-3 pointer f1" style={{ top: '50%' }} onClick={p.leftButton}>
        {'<'}
      </div>
      <div className="absolute right-3 pointer f1" style={{ top: '50%' }} onClick={p.rightButton}>
        {'>'}
      </div>
    </div>
  )
}
